language: node_js
node_js:
- '8'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
udpate travis
